/// Error domain for general errors generated by the Google Wallet SDK
extern NSString * const kGWAWalletErrorDomain;

/// Key for a string in the NSError userInfo dictionary for kGWAWalletErrorDomain errors containing
/// messages specifically for the integrator to aid debugging process.
///
/// These messages should not be shown to the user.
extern NSString * const kGWAWalletErrorDescriptionForIntegratorKey;

/// An enumeration of all error codes generated by Google Wallet SDK.
/// If an error is returned via the GWAWalletClientDelegate interface, the
/// error domain will be kGWAWalletErrorDomain, and the error code will be one of the
/// values from this enum.  If additional details about the error are available, they
/// will be returned in userInfo.
typedef NS_ENUM(NSInteger, GWAWalletErrorCode) {

  /// There was an unexpected authentication error.
  /// Not immediately recoverable.
  kGWAWalletErrorAuthenticationFailure = -599,

  /// There are problems with buyer's account, for example, the user closed the account.
  /// Not immediately recoverable.
  kGWAWalletErrorBuyerAccountError = -512,

  /// The buyer cancelled the transaction in the Google Wallet UI.
  kGWAWalletErrorBuyerCancelled = -521,

  /// There was an integration error, such as a missing callback URL scheme, or
  /// a loadFullWallet call that was not preceded by a loadMaskedWallet call.
  /// Not immediately recoverable.
  kGWAWalletErrorIntegrationError = -598,

  /// Problems were encountered in our internal systems.  Try again later, or contact us
  /// if the problem persists.
  /// Not immediately recoverable.
  kGWAWalletErrorInternalError = -562,

  /// A parameter is missing or contains invalid content.
  /// Not immediately recoverable.
  kGWAWalletErrorInvalidParameters = -542,

  /// loadFullWallet or changeMaskedWallet was called outside the context of a transaction.
  /// For example, loadFullWallet was called without a successful call to loadMaskedWallet.
  /// Not immediately recoverable.
  kGWAWalletErrorInvalidTransaction = -597,

  /// There was a problem with the merchant account, for example the account has been closed.
  /// Not immediately recoverable.
  kGWAWalletErrorMerchantAccountError = -551,

  /// The Google Wallet Instant Buy service has been temporarily disabled.
  /// Not immediately recoverable.
  kGWAWalletErrorServiceUnavailable = -561,

  /// The requested cart amount exceeds the buyer's spending limit.  Users may be able
  /// to complete the transaction by modifying the contents of the cart, trying with a
  /// a different card, or trying with a different user account.
  kGWAWalletErrorSpendingLimitExceeded = -532,

  /// An unknown error occured.
  /// Not immediately recoverable.
  kGWAWalletErrorUnknown = -500,

  /// This version of the merchant library is no longer supported.
  /// Not immediately recoverable.
  kGWAWalletErrorUnsupportedAPIVersion = -543,
};
